# Generated by Django 3.1.4 on 2020-12-16 18:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0002_auto_20201216_1620'),
        ('game', '0002_auto_20201216_1523'),
    ]

    operations = [
    ]
