# Generated by Django 3.1.4 on 2020-12-17 13:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0003_merge_20201216_1954'),
        ('game', '0004_auto_20201216_2057'),
    ]

    operations = [
    ]
