<<<<<<< HEAD
# Generated by Django 3.1.2 on 2020-10-21 08:25

import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion
=======
# Generated by Django 3.1.2 on 2020-10-21 11:51

from django.db import migrations, models
>>>>>>> refs/remotes/origin/main


class Migration(migrations.Migration):

    initial = True

    dependencies = [
<<<<<<< HEAD
        ('auth', '0012_alter_user_first_name_max_length'),
=======
>>>>>>> refs/remotes/origin/main
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
<<<<<<< HEAD
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='auth.user')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            bases=('auth.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
=======
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=50)),
>>>>>>> refs/remotes/origin/main
            ],
        ),
    ]
