# Generated by Django 3.1.4 on 2020-12-16 03:03

from django.db import migrations

def load_moves(apps, schema_editor) :
    Move = apps.get_model("ai", "Move")
    for x in range(2) :
        for y in range(2) :
            Move.objects.create(moveX=x, moveY=y)

class Migration(migrations.Migration):

    dependencies = [
        ('ai', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(load_moves)
    ]
