# Generated by Django 3.1.4 on 2020-12-16 03:03

from django.db import migrations

def load_moves(apps, schema_editor) :
    Move = apps.get_model("ai", "Move")
    for i in range(-1, 2, 2) :
        Move.objects.create(moveX=i, moveY=0)
        Move.objects.create(moveX=0, moveY=i)

class Migration(migrations.Migration):

    dependencies = [
        ('ai', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(load_moves)
    ]
