# Generated by Django 3.1.4 on 2020-12-17 14:22

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai', '0003_auto_20201217_1302'),
    ]

    operations = [
        migrations.AlterField(
            model_name='esperance',
            name='esperance',
            field=models.FloatField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1)]),
        ),
    ]
